typography_spectrum: 0.4134922935627401
color:
  brandStrength: 0.24813803704455495
  lightness: 0.7745024485047907
  saturation: 0.12938226317055523
  rhythmicContrast: 0.9213613807223737
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
layout_spectrum: 0.5658053536899388
name: Curl Queen
navigation:
  - id: 8bb6d240-ebb8-4213-9fe2-75238b8b6449
    name: About Quinn
    type: content
  - url: 'https://www.schedulicity.com/scheduling/QBHTL6'
    name: 'Make an Appointment '
    type: external
  - url: 'https://www.instagram.com/curl_whisperer/'
    name: Follow Me on Instagram
    type: external
title: Curl Queen
description: "\_Hello, I do hair."
