name: Curl Queen
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/357d3dbf-2b34-400b-baf9-d0ff12a72009.png
layout_spectrum: 0.5658053536899388
typography_spectrum: 0.4134922935627401
style: the-composer
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/10864d92-e156-4bdc-9d83-12109521ceba.png
navigation:
  - id: 8bb6d240-ebb8-4213-9fe2-75238b8b6449
    name: About Quinn
    type: content
  - url: 'https://www.schedulicity.com/scheduling/QBHTL6'
    name: 'Make an Appointment '
    type: external
  - url: 'https://www.instagram.com/curl_whisperer/'
    name: Follow Me on Instagram
    type: external
title: Curl Queen
description: "\_Hello, I do hair."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/c3b85c03-7da6-4839-9549-c074a51b3038.png
  type: null
  appId: null
color:
  brandColors:
    - '#c2b1c2'
    - '#a295a7'
    - '#897580'
    - '#33222b'
    - '#813535'
  brandStrength: 0.24813803704455495
  lightness: 0.7745024485047907
  saturation: 0.12938226317055523
  rhythmicContrast: 0.9213613807223737
purpose: []
